apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: elt-argo-example
spec:
  entrypoint: elt-pipeline
  templates:
    - name: elt-pipeline
      dag:
        tasks:
          - name: extract-data
            templateRef:
              name: extract
              template: extract-template
          - name: load-data
            dependencies: [extract-data]
            templateRef:
              name: load
              template: load-template
            # arguments:
            #   artifacts:
            #   - name: extracted-data
            #     from: "{{tasks.extract-data.outputs.artifacts.extracted-data}}"
          - name: transform-data
            dependencies: [load-data]
            templateRef:
              name: transform
              template: transform-template
            # arguments:
            #   artifacts:
            #     - name: loaded-data
            #       from: "{{dag.tasks.load-data.outputs.artifacts.loaded-data}}"

  volumes:
  - name: dbt-output-volume
    persistentVolumeClaim:
      claimName: dbt-output-pvc