apiVersion: argoproj.io/v1alpha1
kind: Template
metadata:
  name: load
spec:
  inputs:
    artifacts:
      - name: extracted-data
        path: /tmp/data.csv
  outputs:
    artifacts:
      - name: data
        path: /mnt/data/data.csv
        globalName: data
  container:
    image: alpine:latest
    command: [sh, -c]
    args: |
      mkdir -p /mnt/data
      cp /tmp/data.csv /mnt/data/
    volumeMounts:
      - name: data-volume
        mountPath: /mnt/data