apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: load
spec:
  templates:
  - name: load-template
    # inputs:
    #   artifacts:
    #     - name: extracted-data
    #       path: /mnt/dbt/data.csv
    # outputs:
    #   artifacts:
    #     - name: loaded-data
    #       path: /mnt/dbt/data/data_loaded.csv
    container:
      image: alpine:latest
      command: [sh, -c]
      args: 
        - |
          mkdir -p /mnt/dbt/data
          cp /mnt/dbt/data.csv /mnt/dbt/data_loaded.csv
      volumeMounts:
        - name: dbt-output-volume
          mountPath: /mnt/dbt